name: Actions on Merge to Main
on:
  pull_request_target:
    types:
      - closed
    branches: 'main'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  region: us-east-1
  target: dev

jobs:
  TestBuild:
    runs-on: ubuntu-latest
    steps:
      - name: 'First Step'
        run: |
          echo "the first step command"
      - name: 'Second Step'
        run: |
          echo "the second step command"
        if: ${{ env.target == 'doh' }}
