name: Jobs - Matrix
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      regions:
        required: true
        type: string
      diff:
        required: true
        type: boolean
      preGlobal:
        required: true
        type: boolean
      postGlobal:
        required: true
        type: boolean
      command:
        required: true
        type: string
      parallelStack:
        required: true
        type: boolean

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  PreGlobal:
    if: ${{ inputs.preGlobal == true }}
    name: ${{ inputs.command }} PreGlobal
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Environment: ${{ inputs.env }}"
          echo "Region: ${{ inputs.regions }}"
          echo "Diff: ${{ inputs.diff }}"
          echo "PreGlobal: ${{ inputs.preGlobal }}"
          echo "PostGlobal: ${{ inputs.postGlobal }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deps
        run: |
          echo "Install Deps ${{inputs.command }}"

      - name: PreGlobal
        run: |
          echo "PreGlobal ${{inputs.command }}"

  Stack:
    needs: PreGlobal
    if: always() && (needs.PreGlobal.result == 'success' || needs.PreGlobal.result == 'skipped')
    name: ${{ inputs.command }} Stack ${{ matrix.region }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - name: Info
        run: |
          echo "Environment: ${{ inputs.env }}"
          echo "Region: ${{ inputs.regions }}"
          echo "Diff: ${{ inputs.diff }}"
          echo "PreGlobal: ${{ inputs.preGlobal }}"
          echo "PostGlobal: ${{ inputs.postGlobal }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: AppStack
        run: |
          echo "AppStack ${{inputs.command }} ${{ matrix.region }}"

      - name: SharedStack
        run: |
          echo "SharedStack ${{inputs.command }} ${{ matrix.region }}"

  PostGlobal:
    needs: Stack
    name: ${{ inputs.command }} PostGlobal
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Environment: ${{ inputs.env }}"
          echo "Region: ${{ inputs.regions }}"
          echo "Diff: ${{ inputs.diff }}"
          echo "PreGlobal: ${{ inputs.preGlobal }}"
          echo "PostGlobal: ${{ inputs.postGlobal }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: PostGlobal
        if: ${{ inputs.postGlobal == true }}
        run: |
          echo "PostGlobal ${{inputs.command }}"
