name: Actions on Merge to Main
on:
  pull_request_target:
    types:
      - closed
    branches: 'main'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  PREGLOBAL: true
  POSTGLOBAL: true

jobs:
  TestBuild:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/pipeline_test_build.yaml

  Dev:
    needs: TestBuild
    uses: ./.github/workflows/pipeline_stage.yaml
    with:
      env: dev
      regions: "['us-east-1','ca-central-1']"
      diff: false
      preGlobal: true
      postGlobal: true
      parallelStack: true

  Prod:
    needs: Dev
    uses: ./.github/workflows/pipeline_stage.yaml
    with:
      env: prod
      regions: "['us-east-1','ca-central-1']"
      diff: true
      preGlobal: true
      postGlobal: true
      parallelStack: true
