name: Test and Build
on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deps
        run: |
          echo "Insall..."

      - name: Run Test
        run: |
          echo "Run Test"

      - name: Run Single Build
        run: |
          echo "Run Build"
